# Generated by Django 3.1.3 on 2020-11-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201118_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
    ]
